-- RLS verification for DxMart.
--
-- Proves the security property this whole migration exists to establish: one signed-in
-- user cannot reach another user's data. The old PHP backend had no auth layer at all --
-- every endpoint trusted a user_id sent by the client -- so this is the regression test
-- for that entire class of bug.
--
-- Safe to run against any environment: everything happens inside a transaction that ends
-- in ROLLBACK, so no rows, users or tables survive it.
--
-- Run with:  supabase db query --file supabase/tests/rls_verification.sql
--        or: paste into the SQL editor / MCP execute_sql
--
-- Expect 13 rows, all PASS. Any '*** FAIL ***' is a security regression -- do not deploy.
--
-- Note this file seeds its own miniature schema rather than assuming the real one is
-- present, so it can be run against an empty project. The policy definitions below are
-- copied verbatim from 20260724000002_rls_policies.sql; if you change a policy there,
-- change it here too or this test stops meaning anything.

BEGIN;

-- ---- miniature schema ----------------------------------------------------
create table public.main_category (id bigint generated by default as identity primary key, name text);
create table public.products (id bigint generated by default as identity primary key, name text not null, main_category_id bigint not null references public.main_category(id));
create table public.product_variants (id bigint generated by default as identity primary key, product_id bigint not null references public.products(id), name text not null, price numeric(10,2) not null, selling_price numeric(10,2) not null);
create table public.coupon (id bigint generated by default as identity primary key, title text not null, code_name text not null, discount integer not null, status text not null);
create table public.user_profiles (id uuid primary key references auth.users(id) on delete cascade, name text, status text not null default 'active');
create table public.cart_items (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, product_id bigint not null references public.products(id), variant_id bigint references public.product_variants(id), quantity integer not null default 1 check (quantity > 0));
create table public.orders (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, total_amount numeric(10,2) not null, final_amount numeric(10,2) not null);
create table public.order_items (id bigint generated by default as identity primary key, order_id bigint not null references public.orders(id) on delete cascade, quantity integer not null check (quantity > 0));
create table public.delivery_boy (id bigint generated by default as identity primary key, name text not null, mobile text not null, address text);

alter table public.main_category enable row level security;
alter table public.products enable row level security;
alter table public.product_variants enable row level security;
alter table public.coupon enable row level security;
alter table public.user_profiles enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.delivery_boy enable row level security;

-- ---- policies under test (verbatim from the migration) -------------------
revoke all on all tables in schema public from anon, authenticated;

grant select on public.main_category, public.products, public.product_variants to anon, authenticated;
create policy "products_select_all" on public.products for select to anon, authenticated using (true);
create policy "main_category_select_all" on public.main_category for select to anon, authenticated using (true);
create policy "product_variants_select_all" on public.product_variants for select to anon, authenticated using (true);

grant select on public.coupon to anon, authenticated;
create policy "coupon_select_public_only" on public.coupon for select to anon, authenticated using (status = 'Public');

grant select, update on public.user_profiles to authenticated;
create policy "user_profiles_select_own" on public.user_profiles for select to authenticated using ((select auth.uid()) = id);

grant select, insert, update, delete on public.cart_items to authenticated;
create policy "cart_items_select_own" on public.cart_items for select to authenticated using ((select auth.uid()) = user_id);
create policy "cart_items_insert_own" on public.cart_items for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "cart_items_update_own" on public.cart_items for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "cart_items_delete_own" on public.cart_items for delete to authenticated using ((select auth.uid()) = user_id);

grant select on public.orders, public.order_items to authenticated;
create policy "orders_select_own" on public.orders for select to authenticated using ((select auth.uid()) = user_id);
create policy "order_items_select_own" on public.order_items for select to authenticated
  using (exists (select 1 from public.orders o where o.id = order_items.order_id and o.user_id = (select auth.uid())));

-- ---- two users, each with their own data ---------------------------------
insert into auth.users (id, instance_id, aud, role, email, created_at, updated_at)
values ('11111111-1111-1111-1111-111111111111','00000000-0000-0000-0000-000000000000','authenticated','authenticated','a@t.local',now(),now()),
       ('22222222-2222-2222-2222-222222222222','00000000-0000-0000-0000-000000000000','authenticated','authenticated','b@t.local',now(),now());
insert into public.user_profiles (id,name) values ('11111111-1111-1111-1111-111111111111','A'),('22222222-2222-2222-2222-222222222222','B');
insert into public.main_category (id,name) values (1,'Dals');
insert into public.products (id,name,main_category_id) values (1,'Moong Dal',1);
insert into public.product_variants (id,product_id,name,price,selling_price) values (1,1,'1kg',100,90);
insert into public.coupon (id,title,code_name,discount,status) values (1,'Pub','HOLI20',20,'Public'),(2,'Sec','SECRET99',99,'Private');
insert into public.delivery_boy (id,name,mobile,address) values (1,'Rider','9999999999','Rider home');
insert into public.cart_items (user_id,product_id,variant_id,quantity) values ('11111111-1111-1111-1111-111111111111',1,1,2),('22222222-2222-2222-2222-222222222222',1,1,5);
insert into public.orders (id,user_id,total_amount,final_amount) values (1,'11111111-1111-1111-1111-111111111111',180,180),(2,'22222222-2222-2222-2222-222222222222',450,450);
insert into public.order_items (order_id,quantity) values (1,2),(2,5);

create temp table results(n int, check_name text, expected text, actual text, pass boolean);
grant all on results to authenticated, anon;

do $$
declare v text;
begin
  -- act as User A
  perform set_config('role','authenticated',true);
  perform set_config('request.jwt.claims','{"sub":"11111111-1111-1111-1111-111111111111","role":"authenticated"}',true);

  select count(*)::text into v from public.cart_items;
  insert into results values (1,'A sees only own cart row (B hidden)','1',v,v='1');
  select coalesce(max(quantity)::text,'-') into v from public.cart_items;
  insert into results values (2,'A sees own qty 2, not B qty 5','2',v,v='2');
  select count(*)::text into v from public.orders;
  insert into results values (3,'A sees only own order','1',v,v='1');
  select count(*)::text into v from public.order_items;
  insert into results values (4,'A sees only own order_items (inherited)','1',v,v='1');
  select count(*)::text into v from public.user_profiles;
  insert into results values (5,'A sees only own profile','1',v,v='1');
  select count(*)::text into v from public.products;
  insert into results values (6,'A can read catalog','1',v,v='1');
  select count(*)::text into v from public.coupon;
  insert into results values (7,'A sees Public coupon only, Private hidden','1',v,v='1');

  begin
    select count(*)::text into v from public.delivery_boy;
    insert into results values (8,'Rider PII (delivery_boy) unreachable','denied','READABLE '||v,false);
  exception when insufficient_privilege then
    insert into results values (8,'Rider PII (delivery_boy) unreachable','denied','denied',true);
  end;

  update public.cart_items set quantity=99 where quantity=5;
  get diagnostics v = row_count;
  insert into results values (9,'A cannot modify B cart row','0 rows',v||' rows',v='0');

  begin
    update public.cart_items set user_id='22222222-2222-2222-2222-222222222222' where quantity=2;
    get diagnostics v = row_count;
    insert into results values (10,'A cannot hand own row to B (WITH CHECK)','blocked',v||' rows updated',false);
  exception when others then
    insert into results values (10,'A cannot hand own row to B (WITH CHECK)','blocked','blocked '||sqlstate,true);
  end;

  begin
    insert into public.orders (user_id,total_amount,final_amount) values ('11111111-1111-1111-1111-111111111111',999,0.01);
    insert into results values (11,'A cannot self-price an order (no INSERT policy)','blocked','INSERT SUCCEEDED',false);
  exception when others then
    insert into results values (11,'A cannot self-price an order (no INSERT policy)','blocked','blocked '||sqlstate,true);
  end;

  -- act as an anonymous visitor
  perform set_config('role','anon',true);
  perform set_config('request.jwt.claims','{"role":"anon"}',true);

  select count(*)::text into v from public.products;
  insert into results values (12,'Anonymous can browse catalog','1',v,v='1');
  begin
    select count(*)::text into v from public.cart_items;
    insert into results values (13,'Anonymous sees no cart data','0 or denied',v,v='0');
  exception when insufficient_privilege then
    insert into results values (13,'Anonymous sees no cart data','0 or denied','denied',true);
  end;
end $$;

RESET ROLE;
select n, check_name, expected, actual,
       case when pass then 'PASS' else '*** FAIL ***' end as result
from results order by n;

ROLLBACK;
