// The catalog, indexed for matching what people actually say.
//
// The old matcher ran `ilike('alias', '%token%')` with no ORDER BY and
// `limit(1)`, so it took an arbitrary row — in practice the lowest id. Against
// aliases that were generated by splitting product titles on whitespace, that
// produced:
//
//   "chawal" / "basmati" -> Bhagyalakshmi Rice *Flour*, not the rice
//   "aashirvaad"         -> a *Fortune* atta
//   "for", "pack", "100" -> matchable "products"
//
// And because it was a substring match against a single alias, a natural
// phrase like "aashirvaad atta" matched *nothing*: no single alias contains
// that whole string. Speaking properly was strictly worse than saying one word.
//
// So: load the catalog once, drop the junk aliases, and score candidates in
// memory. 35 SKUs is small enough that this is faster than the queries it
// replaces, and it can be tested without a database.

import type { SupabaseClient } from "jsr:@supabase/supabase-js@2";

export type Variant = {
  id: number;
  name: string | null;
  price: number;
  selling_price: number;
  stock: number;
};

export type Product = {
  id: number;
  name: string;
  name_hi: string | null;
  aliases: string[];
  variants: Variant[];
  image_url: string;
};

export type Index = { products: Product[]; builtAt: number };

const TTL_MS = 60_000;
let cached: Index | null = null;

// Auto-split title tokens that identify nothing. Kept deliberately short: the
// shared-alias rule below does most of the work.
const ALIAS_STOPLIST = new Set([
  "for", "and", "the", "with", "pack", "packs", "brand", "free", "buy", "get",
  "no", "of", "in", "world", "s", "new", "best", "combo", "offer", "raw",
  "pure", "fresh", "original", "premium", "special", "value", "size",
]);

/** True if this alias is worth indexing at all. */
export function usefulAlias(alias: string, sharedBy: number): boolean {
  const a = alias.toLowerCase().trim();
  if (a.length < 2) return false;
  if (ALIAS_STOPLIST.has(a)) return false;
  if (/^\d+$/.test(a)) return false;
  // An alias claimed by three or more products identifies none of them, and
  // under the old limit(1) it silently resolved to whichever came first.
  if (sharedBy >= 3) return false;
  return true;
}

const norm = (s: string) =>
  s.toLowerCase().normalize("NFKD").replace(/\s+/g, " ").trim();

export function buildIndex(rows: RawProduct[]): Index {
  const sharedBy = new Map<string, number>();
  for (const p of rows) {
    const seen = new Set<string>();
    for (const a of p.product_aliases ?? []) {
      const k = norm(a.alias ?? "");
      if (k && !seen.has(k)) {
        seen.add(k);
        sharedBy.set(k, (sharedBy.get(k) ?? 0) + 1);
      }
    }
  }

  const products: Product[] = [];
  for (const p of rows) {
    const variants = (p.product_variants ?? []).map((v) => ({
      id: v.id,
      name: v.name,
      price: Number(v.price ?? 0),
      selling_price: Number(v.selling_price ?? 0),
      stock: Number(v.stock ?? 0),
    }));
    if (variants.length === 0) continue; // nothing buyable

    const aliases = (p.product_aliases ?? [])
      .map((a) => norm(a.alias ?? ""))
      .filter((a) => a && usefulAlias(a, sharedBy.get(a) ?? 1));

    products.push({
      id: p.id,
      name: p.name ?? "",
      name_hi: p.name_hi ?? null,
      aliases: [...new Set(aliases)],
      variants,
      image_url: p.product_images?.[0]?.image_url ?? "",
    });
  }
  return { products, builtAt: Date.now() };
}

type RawProduct = {
  id: number;
  name: string | null;
  name_hi: string | null;
  product_aliases: { alias: string | null }[] | null;
  product_variants: {
    id: number;
    name: string | null;
    price: number | string | null;
    selling_price: number | string | null;
    stock: number | null;
  }[] | null;
  product_images: { image_url: string | null }[] | null;
};

export async function loadIndex(
  db: SupabaseClient,
  force = false,
): Promise<Index> {
  if (!force && cached && Date.now() - cached.builtAt < TTL_MS) return cached;

  const { data, error } = await db
    .from("products")
    .select(
      "id, name, name_hi, product_aliases(alias), " +
        "product_variants(id, name, price, selling_price, stock), " +
        "product_images(image_url)",
    )
    .eq("is_active", true)
    .order("id");
  if (error) throw error;

  cached = buildIndex((data ?? []) as unknown as RawProduct[]);
  return cached;
}

/** Test seam. */
export function _setIndex(i: Index | null) {
  cached = i;
}

export type Scored = { product: Product; score: number; why: string };

/**
 * Ranks products against a spoken phrase.
 *
 * Multi-word input is handled by scoring the phrase as a whole AND its tokens,
 * so "aashirvaad atta" now resolves — the old substring query could not match
 * it at all because no single alias contains that string.
 */
export function scoreProducts(index: Index, spoken: string): Scored[] {
  const phrase = norm(spoken);
  if (!phrase) return [];
  const tokens = phrase.split(" ").filter((t) => t.length >= 2);

  const out: Scored[] = [];
  for (const p of index.products) {
    let score = 0;
    let why = "";
    const name = norm(p.name);
    const nameHi = p.name_hi ? norm(p.name_hi) : "";

    // The product's own NAME outranks any alias, deliberately.
    //
    // These aliases were generated by splitting titles, and several are simply
    // wrong: "aashirvaad" sits on a *Fortune* atta. Both products then claimed
    // the word equally and the tie fell to whichever had the lower id, which is
    // how "aashirvaad" returned Fortune. A name is authoritative; an alias is a
    // hint.
    if (name === phrase || nameHi === phrase) {
      score = Math.max(score, 200);
      why = "name-exact";
    }
    if (name.includes(phrase) || (nameHi && nameHi.includes(phrase))) {
      score = Math.max(score, 150 + phrase.length);
      why = why || "name-contains";
    }
    if (p.aliases.includes(phrase)) {
      score = Math.max(score, 100 + phrase.length);
      why = why || "alias-exact";
    }

    // Per-token evidence, with the same name-over-alias ordering. Longer
    // tokens are stronger: "aashirvaad" says far more than "ka".
    let tokenHits = 0;
    for (const t of tokens) {
      if (name.includes(t) || (nameHi && nameHi.includes(t))) {
        tokenHits++;
        score += 30 + t.length;
      } else if (p.aliases.includes(t)) {
        tokenHits++;
        score += 15 + t.length;
      } else if (p.aliases.some((a) => a.includes(t) && t.length >= 4)) {
        tokenHits++;
        score += 8 + t.length;
      }
    }
    // Every token accounted for is a much stronger signal than one of three.
    if (tokens.length > 1 && tokenHits === tokens.length) score += 40;

    if (score > 0) {
      out.push({ product: p, score, why: why || `tokens:${tokenHits}` });
    }
  }

  out.sort((a, b) => b.score - a.score || a.product.id - b.product.id);
  return out;
}

export type MatchResult =
  | { kind: "none" }
  | { kind: "one"; product: Product }
  | { kind: "ambiguous"; candidates: Product[] };

/**
 * Best product for a spoken phrase.
 *
 * Reports ambiguity instead of hiding it. "chawal" genuinely matches both the
 * rice and the rice *flour* — the flour is legitimately "chawal ka atta" — and
 * the old code resolved that silently by id order, which is how asking for rice
 * returned flour. A near-tie is a question, not a decision.
 */
export function matchOne(index: Index, spoken: string): MatchResult {
  const ranked = scoreProducts(index, spoken);
  if (ranked.length === 0) return { kind: "none" };

  const best = ranked[0];
  const runnerUp = ranked[1];
  // Within 20% is not a winner, it is a coin toss. Tuned against the real
  // catalog: "aata" alone stays a question (two attas, no way to choose), while
  // "aashirvaad atta" resolves, because naming the brand is a clear signal.
  if (runnerUp && runnerUp.score >= best.score * 0.8) {
    return {
      kind: "ambiguous",
      candidates: ranked
        .filter((r) => r.score >= best.score * 0.8)
        .slice(0, 3)
        .map((r) => r.product),
    };
  }
  return { kind: "one", product: best.product };
}

/** Best product for a spoken phrase, or null when nothing is convincing. */
export function findProduct(index: Index, spoken: string): Product | null {
  const ranked = scoreProducts(index, spoken);
  return ranked.length > 0 ? ranked[0].product : null;
}

/** Compact catalog for an LLM prompt: ids, names, aliases, packs, stock. */
export function renderForPrompt(index: Index): string {
  const lines: string[] = [];
  for (const p of index.products) {
    const hi = p.name_hi ? ` | hi: ${p.name_hi}` : "";
    lines.push(`P${p.id} "${p.name}"${hi}`);
    if (p.aliases.length) lines.push(`  aka: ${p.aliases.join(", ")}`);
    lines.push(
      "  " +
        p.variants
          .map((v) => `V${v.id} "${v.name ?? ""}" Rs${v.selling_price} stock:${v.stock}`)
          .join(" | "),
    );
  }
  return lines.join("\n");
}
