"""The catalog, rendered for a language model rather than for a screen.

A 1:1 port of the TypeScript that used to live in
``supabase/functions/voice-relay/catalog.ts``.

DxMart carries ~35 active SKUs, small enough to hand the model the entire
catalog up front. That removes a whole class of problem: no search round trip on
the critical path, and matching "do kilo aata" stops being a substring ``ilike``
against ``product_aliases`` (first hit wins) and becomes the model reading full
product names in context.

Read with the anon key, not a user token: products are world-readable, so the
snapshot is identical for everyone and can be cached process-wide.

This stops scaling somewhere around 200 SKUs. Past that, drop the snapshot and
promote ``search_products`` to the primary path.
"""

from __future__ import annotations

import os
import re
import time

import httpx

_TTL_SECONDS = 60.0
_cache: tuple[str, float] | None = None

_SELECT = (
    "id,name,name_hi,main_category(name),"
    "product_variants(id,name,selling_price,stock),"
    "product_aliases(alias)"
)

# Aliases in this catalog were generated by splitting product titles on
# whitespace, so alongside the genuinely useful Hindi ones (aata, gehu, daal,
# chawal) they include pure noise -- "for", "pack", "brand", "100", "fresh" --
# and some outright wrong cross-brand claims ("aashirvaad" on a *Fortune* atta,
# "chawal"/"basmati" on a rice *flour*, "butter" on a ghee).
#
# That is not cosmetic. Fed to the model verbatim, "do kilo aata" resolved to
# Bhagyalakshmi Rice Flour: it carries the alias "flour" and happens to have a
# 2 Kg variant, while the actual atta only comes in 5 kg and 10 kg. The model
# reads full product names too, so the fix is simply to stop feeding it the
# tokens that carry no signal.
_ALIAS_STOPLIST = {
    "for", "and", "the", "with", "pack", "brand", "free", "buy", "get", "no",
    "of", "in", "1", "2", "100", "world", "s", "new", "best", "combo", "offer",
}

_DIGITS = re.compile(r"^\d+$")


def _useful_alias(alias: str, shared_by: int) -> bool:
    """True if this alias is worth showing the model."""
    a = alias.lower().strip()
    if len(a) < 2:
        return False
    if a in _ALIAS_STOPLIST:
        return False
    if _DIGITS.match(a):
        return False
    # An alias claimed by three or more products identifies none of them, and
    # actively pulls the model toward whichever happens to be listed first.
    if shared_by >= 3:
        return False
    return True


def _render(rows: list[dict]) -> str:
    # How many distinct products claim each alias, so shared ones can be dropped.
    shared_by: dict[str, int] = {}
    for p in rows:
        seen: set[str] = set()
        for a in p.get("product_aliases") or []:
            k = (a.get("alias") or "").lower().strip()
            if k and k not in seen:
                seen.add(k)
                shared_by[k] = shared_by.get(k, 0) + 1

    lines: list[str] = []
    for p in rows:
        variants = sorted(
            p.get("product_variants") or [],
            key=lambda v: float(v.get("selling_price") or 0),
        )
        # A product with no variant cannot be added to a cart, so leaving it in
        # the prompt would only invite the model to offer something unbuyable.
        if not variants:
            continue

        aliases = [
            a
            for a in ((x.get("alias") or "").strip() for x in (p.get("product_aliases") or []))
            if a and _useful_alias(a, shared_by.get(a.lower(), 1))
        ]

        cat = p.get("main_category") or {}
        if isinstance(cat, list):
            cat = cat[0] if cat else {}
        cat_name = cat.get("name") or ""

        hi = f" | hi: {p['name_hi']}" if p.get("name_hi") else ""
        lines.append(f'P{p["id"]} "{p.get("name") or ""}"{hi} [{cat_name}]')
        if aliases:
            lines.append("  aka: " + ", ".join(aliases))
        lines.append(
            "  "
            + " | ".join(
                f'V{v["id"]} "{v.get("name") or ""}" '
                f'Rs{float(v.get("selling_price") or 0):g} stock:{v.get("stock") or 0}'
                for v in variants
            )
        )

    return "\n".join(lines)


async def fetch(force: bool = False) -> str:
    """The catalog snapshot, cached process-wide for 60s."""
    global _cache
    if not force and _cache and (time.monotonic() - _cache[1]) < _TTL_SECONDS:
        return _cache[0]

    base = os.environ["SUPABASE_URL"].rstrip("/")
    key = os.environ["SUPABASE_ANON_KEY"]

    async with httpx.AsyncClient(timeout=10.0) as client:
        res = await client.get(
            f"{base}/rest/v1/products",
            params={"select": _SELECT, "is_active": "eq.true", "order": "id"},
            headers={"apikey": key, "Authorization": f"Bearer {key}"},
        )
        res.raise_for_status()
        rows = res.json()

    text = _render(rows)
    _cache = (text, time.monotonic())
    return text


def cached() -> str | None:
    """The snapshot if one is already warm, without doing I/O."""
    return _cache[0] if _cache else None
