// The catalog, rendered for a language model rather than for a screen.
//
// DxMart carries ~35 active SKUs. That is small enough to hand the model the
// entire catalog up front, which removes a whole class of problem: there is no
// search round trip on the critical path, and matching "do kilo aata" stops
// being a substring `ilike` against product_aliases (first hit wins, so asking
// for `chawal` currently returns Bhagyalakshmi Rice *Flour*) and becomes the
// model reading full product names in context.
//
// This stops scaling somewhere around 200 SKUs. Past that, drop the snapshot
// and promote search_products to the primary path.

import { SupabaseClient } from "jsr:@supabase/supabase-js@2";

const TTL_MS = 60_000;

let cached: { text: string; at: number } | null = null;

type VariantRow = {
  id: number;
  name: string | null;
  selling_price: number | string | null;
  stock: number | null;
};

type ProductRow = {
  id: number;
  name: string | null;
  name_hi: string | null;
  product_variants: VariantRow[] | null;
  product_aliases: { alias: string | null }[] | null;
  main_category: { name: string | null } | { name: string | null }[] | null;
};

function categoryName(
  c: ProductRow["main_category"],
): string {
  if (!c) return "";
  const one = Array.isArray(c) ? c[0] : c;
  return one?.name ?? "";
}

// Aliases in this catalog were generated by splitting product titles on
// whitespace, so alongside the genuinely useful Hindi ones (aata, gehu, daal,
// chawal) they include pure noise -- "for", "pack", "brand", "100", "fresh" --
// and some outright wrong cross-brand claims ("aashirvaad" on a *Fortune*
// atta, "chawal"/"basmati" on a rice *flour*, "butter" on a ghee).
//
// That is not cosmetic. Fed to the model verbatim, "do kilo aata" resolved to
// Bhagyalakshmi Rice Flour: it carries the alias "flour" and happens to have a
// 2 Kg variant, while the actual atta only comes in 5 kg and 10 kg. The model
// reads full product names too, so the fix is simply to stop feeding it the
// tokens that carry no signal.
const ALIAS_STOPLIST = new Set([
  "for", "and", "the", "with", "pack", "brand", "free", "buy", "get", "no",
  "of", "in", "1", "2", "100", "world", "s", "new", "best", "combo", "offer",
]);

/** True if this alias is worth showing the model. */
function usefulAlias(alias: string, sharedBy: number): boolean {
  const a = alias.toLowerCase().trim();
  if (a.length < 2) return false;
  if (ALIAS_STOPLIST.has(a)) return false;
  if (/^\d+$/.test(a)) return false;
  // An alias claimed by three or more products identifies none of them, and
  // actively pulls the model toward whichever happens to be listed first.
  if (sharedBy >= 3) return false;
  return true;
}

/**
 * A compact plain-text rendering of every active product, its variants (with
 * live price and stock) and its Hindi/Hinglish aliases.
 *
 * Read through the *caller's* RLS client so `is_active` filtering and row
 * visibility stay exactly what a signed-in user would see — the voice agent
 * must never be able to surface a product the shop has withdrawn.
 */
export async function buildCatalogSnapshot(
  db: SupabaseClient,
): Promise<string> {
  if (cached && Date.now() - cached.at < TTL_MS) return cached.text;

  const { data, error } = await db
    .from("products")
    .select(
      "id, name, name_hi, main_category(name), product_variants(id, name, selling_price, stock), product_aliases(alias)",
    )
    .eq("is_active", true)
    .order("id");

  if (error) throw new Error(`catalog read failed: ${error.message}`);

  const rows = (data ?? []) as unknown as ProductRow[];

  // How many distinct products claim each alias, so shared ones can be dropped.
  const sharedBy = new Map<string, number>();
  for (const p of rows) {
    const seen = new Set<string>();
    for (const a of p.product_aliases ?? []) {
      const k = a.alias?.toLowerCase().trim();
      if (k && !seen.has(k)) {
        seen.add(k);
        sharedBy.set(k, (sharedBy.get(k) ?? 0) + 1);
      }
    }
  }

  const lines: string[] = [];

  for (const p of rows) {
    const variants = (p.product_variants ?? [])
      .slice()
      .sort((a, b) => Number(a.selling_price ?? 0) - Number(b.selling_price ?? 0));

    // A product with no variant cannot be added to a cart, so leaving it in the
    // prompt would only invite the model to offer something unbuyable.
    if (variants.length === 0) continue;

    const aliases = (p.product_aliases ?? [])
      .map((a) => a.alias?.trim())
      .filter((a): a is string => !!a)
      .filter((a) => usefulAlias(a, sharedBy.get(a.toLowerCase()) ?? 1));

    const cat = categoryName(p.main_category);
    const hi = p.name_hi ? ` | hi: ${p.name_hi}` : "";
    lines.push(`P${p.id} "${p.name ?? ""}"${hi} [${cat}]`);

    if (aliases.length) {
      lines.push(`  aka: ${aliases.join(", ")}`);
    }

    lines.push(
      "  " +
        variants
          .map(
            (v) =>
              `V${v.id} "${v.name ?? ""}" Rs${Number(v.selling_price ?? 0)}` +
              ` stock:${v.stock ?? 0}`,
          )
          .join(" | "),
    );
  }

  const text = lines.join("\n");
  cached = { text, at: Date.now() };
  return text;
}

/** Forces the next call to re-read. Used after a catalog write in tests. */
export function invalidateCatalog(): void {
  cached = null;
}
