-- DxMart: initial Postgres schema, converted from the live MariaDB `thok24` database.
--
-- Scope: consumer-only (households). There is deliberately NO role/account_type column
-- and nothing anywhere gates on user type. `wholesale_price` is carried across for
-- structural fidelity but is never referenced.
--
-- RLS is enabled here on every table but NO policies are created — policies land in the
-- next migration (Phase 2) so they can be reviewed on their own. Until then, RLS-enabled
-- tables with no policy deny all access to anon/authenticated, which is the safe default.
--
-- Conversions applied throughout:
--   int(11) AUTO_INCREMENT  -> bigint generated BY DEFAULT as identity
--                              (BY DEFAULT, not ALWAYS, so Phase 5 can preserve legacy ids)
--   decimal/double(10,2)    -> numeric(10,2)          (never float for money)
--   varchar dates           -> timestamptz / date      (see per-column notes)
--   latin1 tables           -> UTF-8 (Postgres is UTF-8 throughout)
--   int user_id             -> uuid referencing auth.users(id)

-- ---------------------------------------------------------------------------
-- Schemas
-- ---------------------------------------------------------------------------

-- Staff identity lives outside the exposed `public` schema so it is unreachable
-- via the Data API even if a policy is ever misconfigured.
create schema if not exists private;
revoke all on schema private from anon, authenticated;

-- ---------------------------------------------------------------------------
-- Reference / location
-- ---------------------------------------------------------------------------

create table public.district (
  id            bigint generated by default as identity primary key,
  district_name text not null
);

create table public.city (
  id          bigint generated by default as identity primary key,
  district_id bigint not null references public.district (id) on delete cascade on update cascade,
  city_name   text not null
);
create index city_district_id_idx on public.city (district_id);

-- ---------------------------------------------------------------------------
-- Catalog
-- ---------------------------------------------------------------------------

create table public.main_category (
  id      bigint generated by default as identity primary key,
  name    text,
  name_hi text,   -- Devanagari
  name_hn text,   -- romanized Hinglish
  image   text
);

create table public.products (
  id               bigint generated by default as identity primary key,
  name             text not null,
  name_hi          text,
  name_hn          text,
  description      text not null default '',
  description_hi   text,
  description_hn   text,
  main_category_id bigint not null references public.main_category (id) on delete cascade on update cascade,
  -- Carried across as-is: a comma-separated tag list, e.g.
  -- 'normal,Everyday Essentials,Best selling'. A text[] with a GIN index would be the
  -- idiomatic Postgres shape, but that changes query semantics in the Flutter layer,
  -- so it is left alone here and noted as a follow-up.
  types            text not null default ''
);
create index products_main_category_id_idx on public.products (main_category_id);

create table public.product_variants (
  id              bigint generated by default as identity primary key,
  product_id      bigint not null references public.products (id) on delete cascade on update cascade,
  name            text not null,
  name_hi         text,
  name_hn         text,
  price           numeric(10,2) not null,
  selling_price   numeric(10,2) not null,
  -- Present in the source schema. Intentionally unused: DxMart is consumer-only and
  -- nothing reads this column. Kept so the column is not lost if B2B is revisited.
  wholesale_price numeric(10,2) not null default 0,
  stock           integer not null default 0
);
create index product_variants_product_id_idx on public.product_variants (product_id);

create table public.product_images (
  id         bigint generated by default as identity primary key,
  product_id bigint not null references public.products (id) on delete cascade on update cascade,
  image_url  text not null
);
create index product_images_product_id_idx on public.product_images (product_id);

create table public.product_info (
  id            bigint generated by default as identity primary key,
  product_id    bigint not null references public.products (id) on delete cascade on update cascade,
  attribute     text not null,
  attribute_hi  text,
  attribute_hn  text,
  value         text not null,
  value_hi      text,
  value_hn      text
);
create index product_info_product_id_idx on public.product_info (product_id);

create table public.product_highlights (
  id            bigint generated by default as identity primary key,
  product_id    bigint not null references public.products (id) on delete cascade on update cascade,
  attribute     text not null,
  attribute_hi  text,
  attribute_hn  text,
  value         text not null,
  value_hi      text,
  value_hn      text
);
create index product_highlights_product_id_idx on public.product_highlights (product_id);

-- The Hindi/Hinglish voice-ordering vocabulary (295 rows in the source). This is the
-- highest-value data in the migration: it is hand-built and not reproducible.
create table public.product_aliases (
  id         bigint generated by default as identity primary key,
  product_id bigint not null references public.products (id) on delete cascade on update cascade,
  language   text not null,
  alias      text not null
);
create index product_aliases_product_id_idx on public.product_aliases (product_id);
create index product_aliases_alias_idx on public.product_aliases (alias);

create table public.banner (
  id           bigint generated by default as identity primary key,
  -- Nullable, unlike the source. 3 of 6 source rows point at main_category ids that no
  -- longer exist (5, 6, 9), so a NOT NULL foreign key would reject them outright.
  -- Phase 5 nulls the orphans instead of deleting the banners.
  category_id  bigint references public.main_category (id) on delete set null on update cascade,
  banner_image text not null
);
create index banner_category_id_idx on public.banner (category_id);

create table public.coupon (
  id          bigint generated by default as identity primary key,
  title       text not null,
  description text not null default '',
  code_name   text not null,
  discount    integer not null,
  expiry_date date,          -- was `expri_date` varchar(50), format 'DD-MM-YYYY'
  status      text not null, -- observed: 'Public', 'Private'
  min_amount  integer not null default 0
);
create unique index coupon_code_name_key on public.coupon (lower(code_name));

-- ---------------------------------------------------------------------------
-- Users
-- ---------------------------------------------------------------------------

-- Identity itself lives in auth.users (phone/OTP). This holds the app-side profile.
-- Deliberately no role/account_type column: every user is the same consumer type.
create table public.user_profiles (
  id             uuid primary key references auth.users (id) on delete cascade,
  name           text,
  phone          text,
  status         text not null default 'active',  -- observed: 'active', 'blocked'
  -- Maps back to the old integer users.id so Phase 5 can rewire foreign keys and so
  -- the migration stays auditable. Safe to drop once cutover is verified.
  legacy_user_id bigint unique,
  created_at     timestamptz not null default now()
);

-- Keeps user_profiles in step with auth.users on signup. Must be SECURITY DEFINER to
-- write a row the new user cannot yet write themselves; kept in `private` (not `public`)
-- so it is not exposed as a callable Data API endpoint, with search_path pinned.
create function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.user_profiles (id, phone, name)
  values (
    new.id,
    new.phone,
    nullif(new.raw_user_meta_data ->> 'name', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function private.handle_new_user();

-- Staff allowlist. Consulted only by the admin Edge Function (which then uses the
-- service-role key); never read from a client, never referenced by an RLS policy.
create table private.admin_users (
  id         uuid primary key references auth.users (id) on delete cascade,
  email      text not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- User-owned data
-- ---------------------------------------------------------------------------

create table public.delivery_address (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users (id) on delete cascade,
  name         text not null,
  phone        text not null,
  full_address text not null,
  pin_code     text not null,
  landmark     text
);
create index delivery_address_user_id_idx on public.delivery_address (user_id);

create table public.cart_items (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete cascade on update cascade,
  variant_id bigint references public.product_variants (id) on delete cascade on update cascade,
  quantity   integer not null default 1 check (quantity > 0),
  image_url  text
);
create index cart_items_user_id_idx on public.cart_items (user_id);
create index cart_items_product_id_idx on public.cart_items (product_id);
create index cart_items_variant_id_idx on public.cart_items (variant_id);

create table public.wishlist (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete cascade on update cascade,
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);
create index wishlist_user_id_idx on public.wishlist (user_id);
create index wishlist_product_id_idx on public.wishlist (product_id);

create table public.orders (
  id                  bigint generated by default as identity primary key,
  user_id             uuid not null references auth.users (id) on delete cascade,
  total_amount        numeric(10,2) not null,
  coupon_code         text,
  discount_amount     numeric(10,2) not null default 0,
  delivery_charge     numeric(10,2) not null default 0,
  handling_charge     numeric(10,2) not null default 0,
  final_amount        numeric(10,2) not null,
  status              text not null default 'pending', -- observed: pending, packed, way, delivered
  payment_method      text not null default 'COD',
  -- was varchar 'DD-MM-YYYY hh:mm AM'; Phase 5 parses it as Asia/Kolkata local time
  order_datetime      timestamptz not null default now(),
  delivery_date       date,
  -- NOT a time: the source stores a window like '9 AM - 2 PM', so this stays text.
  delivery_time_window text,
  -- was `location_id`; verified against the data to reference delivery_address.id,
  -- not city.id. Renamed to say so. Nullable + ON DELETE SET NULL so deleting an
  -- address does not delete order history.
  delivery_address_id bigint references public.delivery_address (id) on delete set null,
  gift                text
);
create index orders_user_id_idx on public.orders (user_id);
create index orders_delivery_address_id_idx on public.orders (delivery_address_id);
create index orders_order_datetime_idx on public.orders (order_datetime desc);

create table public.order_items (
  id         bigint generated by default as identity primary key,
  order_id   bigint not null references public.orders (id) on delete cascade,
  -- Nullable, unlike the source: 1 source row references a product that has since been
  -- deleted. Order history must survive catalog deletions, so this is SET NULL rather
  -- than cascading the line item away.
  product_id bigint references public.products (id) on delete set null on update cascade,
  variant_id bigint references public.product_variants (id) on delete set null on update cascade,
  quantity   integer not null check (quantity > 0),
  -- ADDITION beyond a literal port -- flagged for review.
  -- The source captures no price on the line item, so a past order's composition cannot
  -- be reconstructed once catalog prices change; only the order-level total survives.
  -- Nullable so existing rows migrate untouched (NULL = unknown historical price) while
  -- new orders can record it. Drop this column if you would rather port exactly.
  unit_price numeric(10,2),
  image_url  text
);
create index order_items_order_id_idx on public.order_items (order_id);
create index order_items_product_id_idx on public.order_items (product_id);
create index order_items_variant_id_idx on public.order_items (variant_id);

-- Repeat-order recall powering BolKeOrder's "the usual" behaviour.
create table public.regular_orders (
  id              bigint generated by default as identity primary key,
  user_id         uuid not null references auth.users (id) on delete cascade,
  product_id      bigint not null references public.products (id) on delete cascade on update cascade,
  variant_id      bigint not null references public.product_variants (id) on delete cascade on update cascade,
  frequency_score integer not null default 1,
  last_ordered    timestamptz not null default now(),
  unique (user_id, product_id, variant_id)
);
create index regular_orders_user_id_idx on public.regular_orders (user_id);
create index regular_orders_product_id_idx on public.regular_orders (product_id);
create index regular_orders_variant_id_idx on public.regular_orders (variant_id);

create table public.chat_messages (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users (id) on delete cascade,
  -- 'bot' (not 'assistant') is the vocabulary both the source data and process_chat.php
  -- use; keeping it avoids rewriting 68 rows and every insert site in the bot.
  role       text not null default 'user' check (role in ('user', 'bot')),
  message    text not null,
  created_at timestamptz not null default now()
);
create index chat_messages_user_id_created_at_idx on public.chat_messages (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Operations
-- ---------------------------------------------------------------------------

-- Rider roster. Not an auth surface: riders do not log in to this system today, and the
-- source `password` column (plaintext-capable) is deliberately NOT carried across.
create table public.delivery_boy (
  id         bigint generated by default as identity primary key,
  name       text not null,
  email      text,
  mobile     text not null,
  pin_code   text,
  address    text,
  status     text not null default 'active',
  created_at timestamptz not null default now()   -- was `date_time` varchar
);

-- Replaces nine single-row config tables from the source: delivery_charge,
-- delivey_charge (typo duplicate), free_delivey, handling_charge, minimum_order_amout,
-- deliver_time, help_call, help_email, help_whatsapp. Every one of them was EMPTY, so
-- there is nothing to preserve and no reason to carry the typos forward.
create table public.app_settings (
  key        text primary key,
  value      text not null,
  updated_at timestamptz not null default now()
);

comment on table public.app_settings is
  'Single-row config collapsed into key/value. Expected keys: delivery_charge, '
  'free_delivery_threshold, handling_charge, minimum_order_amount, delivery_time, '
  'help_call, help_email, help_whatsapp.';

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
-- Enabled on every table in the exposed `public` schema. No policies yet, so nothing is
-- reachable by anon/authenticated until Phase 2 adds them deliberately.

alter table public.district           enable row level security;
alter table public.city               enable row level security;
alter table public.main_category      enable row level security;
alter table public.products           enable row level security;
alter table public.product_variants   enable row level security;
alter table public.product_images     enable row level security;
alter table public.product_info       enable row level security;
alter table public.product_highlights enable row level security;
alter table public.product_aliases    enable row level security;
alter table public.banner             enable row level security;
alter table public.coupon             enable row level security;
alter table public.user_profiles      enable row level security;
alter table public.delivery_address   enable row level security;
alter table public.cart_items         enable row level security;
alter table public.wishlist           enable row level security;
alter table public.orders             enable row level security;
alter table public.order_items        enable row level security;
alter table public.regular_orders     enable row level security;
alter table public.chat_messages      enable row level security;
alter table public.delivery_boy       enable row level security;
alter table public.app_settings       enable row level security;

-- Defence in depth: `private` is not exposed via the Data API, but enable RLS anyway.
alter table private.admin_users enable row level security;
